### ISSUE TITLE
velacp deploy helm chart set ingress host not applied

### ISSUE THREAD

**Issue by du86796922** [oam-dev/velaux#143]
### What happened:

What you expected to happen:
Trying to deploy velacp using the master branch char, set ingress host does not take effect

### How to reproduce it (as minimally and precisely as possible):
```bash
helm3 --kubeconfig="./kube.config" install velacp ./vela-control-plane --values=./values.yaml --create-namespace
```
values.yaml
```yaml
# Default values for vela-control-plane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: oamdev/vela-control-plane
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 1024

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: velacp.10.20.2.113.xip.io #set ingress host
      paths:
        - path:
          backend:
            serviceName:
            servicePort: 1024
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

healthCheck:
  port: 9550

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

#If non-empty, write log files in this path
logFilePath: ""

#Defines the maximum size a log file can grow to. Unit is megabytes.
#If the value is 0, the maximum file size is unlimited.
logFileMaxSize: 1024

dbURL: 10.20.4.221:27017

dbName: vela

```
helm Generated ingress yaml

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: velacp
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-09-08T01:35:16Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: velacp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vela-control-plane
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: vela-control-plane-0.1.0
  name: velacp-vela-control-plane
  namespace: default
  resourceVersion: "1212405"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/velacp-vela-control-plane
  uid: 7099a49c-f9eb-4a1e-923c-9c35fa42f5fa
spec:
  rules:
  - http:    # not set rules host
      paths:
      - backend:
          serviceName: velacp-vela-control-plane
          servicePort: 1024
status:
  loadBalancer:
    ingress:
    - ip: 10.55.1.107
```
code: not set rules host
https://github.com/oam-dev/velacp/blob/6265e12cdb881dfb754d2727d6f68ddd87840d9b/charts/vela-control-plane/templates/velacp-controller.yaml#L44-L54

add host
```yaml
rules:
    {{- range .Values.ingress.hosts }}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
      host: {{ .host }} #add host
    {{- end }}
```
### Environment:
- Kubernetes version (use kubectl version): v1.17.12
- OS (e.g: cat /etc/os-release): Ubuntu 18.04.5 LTS
- Kernel (e.g. uname -a): 5.4.0-73-generic
- Install tools: helm charts  (master)
- velecp version v0.0.1
