### ISSUE TITLE
[Bug] Gatway trait can't be properly deployed

### ISSUE THREAD

**Issue by BinaryHB0916** [oam-dev/velaux#249]
Creating a simple application as below:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: nginx
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
```

Created webservice successfully. But when creating nginx of Gatway it can't be attached properly, errors showed:

![B08BD5DB-5978-470D-893A-176E27E3F840](https://user-images.githubusercontent.com/57997154/144989289-145cb56f-6955-4c7f-989e-de2127a452b1.png)
