### ISSUE TITLE
ux cannot load env to deploy webservice

### ISSUE THREAD

**Issue by SUMMERLm** [oam-dev/velaux#358]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/92348982/153836766-5ee379ce-f961-44e0-9a07-faa34342f707.png">

**Comment by barnettZQG** [comment]
@SUMMERLm  the data in the Environments page is empty?

**Comment by SUMMERLm** [comment]
@barnettZQG Yes
Cluster info:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/92348982/153972674-1ed4b5de-96d4-4dca-ba08-469d600baabc.png">

Targets:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/92348982/153972933-06b51295-6310-41cc-8aa1-541653cd844f.png">
Environments:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/92348982/153972979-bf0a63bc-571f-40cc-9f4e-b6fbc532362e.png">

**Comment by SUMMERLm** [comment]
I double the reason is that The "Bind enviroment" should get the message from "envs" but not "clusters"
![image](https://user-images.githubusercontent.com/92348982/153973181-d79c6057-91c6-4cc5-becd-6b56f40d5ec2.png)

**Comment by barnettZQG** [comment]
You should look at the api `/api/v1/envs`.

Otherwise, please execute the following command to feedback the result:
```
kubectl get configmap -n kubevela | grep project
```

**Comment by SUMMERLm** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/92348982/153985490-e112673b-377d-4363-bd4e-5c4354ea02b2.png">

**Comment by SUMMERLm** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/92348982/153985518-f37277e3-9994-475a-99ce-3c9756304511.png">

**Comment by SUMMERLm** [comment]
![image](https://user-images.githubusercontent.com/92348982/153985840-849c0daa-d02d-413b-a7d2-b8f204365491.png)

**Comment by barnettZQG** [comment]
@SUMMERLm Did you upgrade from the historical version? then, you should create a default project.

```
apiVersion: v1
binaryData:
  data: eyJjcmVhdGVUaW1lIjoiMjAyMi0wMi0xNFQwMzozNToxOC42NDgwMzQ4WiIsInVwZGF0ZVRpbWUiOiIyMDIyLTAyLTE0VDAzOjM1OjE4LjY0ODA0NjhaIiwibmFtZSI6ImRlZmF1bHQiLCJhbGlhcyI6IkRlZmF1bHQiLCJkZXNjcmlwdGlvbiI6IkRlZmF1bHQgcHJvamVjdCBpcyBjcmVhdGVkIGJ5IHZlbGF1eCBzeXN0ZW0gYXV0b21hdGljYWxseS4ifQ==
kind: ConfigMap
metadata:
  labels:
    name: default
    primaryKey: default
    table: vela_project
  name: veladatabase-vela-project-default
  namespace: kubevela
```
